name: Continuous Deployment

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "microservicetestapp" #Must be unique in Heroku
          heroku_email: "jeppeenevold@gmail.com"
      - name: Test
        run: |
          mvn test -DskipTests=false -Dgroups=slow
          git checkout ${GITHUB_REF#refs/heads/}
          git rebase origin/master
          git branch release
          git push origin release:release
          git push origin :${GITHUB_REF#refs/heads/}